--- =====================================================================
--- SPRINT 1: MASTERING RELATIONAL AND NON-RELATIONAL DATABASE
--- SCRIPT COMPLETO AJUSTADO - ORDEM DE CARGA CORRIGIDA
--- =====================================================================

SET SERVEROUTPUT ON;

--- =====================================================================
--- 1. LIMPEZA TOTAL DA BASE (Lógica de Exceção Atendida)
--- =====================================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_APPOINTMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_ALERT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_CLINICALHISTORY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_PET_VETERINARIAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_PET CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_VETERINARIAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_RESPONSIBLE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_ACCOUNT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_LOG_ERROS_PG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/


--- =====================================================================
--- 2. CRIAÇÃO DAS TABELAS E RESTRIÇÕES INTERNAS
--- =====================================================================

CREATE TABLE T_ACCOUNT (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ) NOT NULL,
    email     VARCHAR2(255) NOT NULL,
    password  VARCHAR2(255) NOT NULL,
    role      VARCHAR2(20) NOT NULL,
    active    NUMBER(1) DEFAULT 1 NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) LOGGING;

ALTER TABLE T_ACCOUNT ADD CONSTRAINT chk_t_account_role CHECK (role IN ('ADMIN', 'RESPONSIBLE', 'VETERINARIAN'));
ALTER TABLE T_ACCOUNT ADD CONSTRAINT chk_t_account_active CHECK (active IN (0, 1));
ALTER TABLE T_ACCOUNT ADD CONSTRAINT T_Account_PK PRIMARY KEY ( id );
ALTER TABLE T_ACCOUNT ADD CONSTRAINT uk_t_account_email UNIQUE ( email );


CREATE TABLE T_RESPONSIBLE (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ) NOT NULL,
    account_id  NUMBER NOT NULL,
    fullName    VARCHAR2(255) NOT NULL,
    cpf         VARCHAR2(14) NOT NULL,
    dateOfBirth DATE,
    phoneNumber VARCHAR2(20),
    address     VARCHAR2(255)
) LOGGING;

ALTER TABLE T_RESPONSIBLE ADD CONSTRAINT T_Responsible_PK PRIMARY KEY ( id );
ALTER TABLE T_RESPONSIBLE ADD CONSTRAINT uk_t_resp_account UNIQUE ( account_id );
ALTER TABLE T_RESPONSIBLE ADD CONSTRAINT uk_t_resp_cpf UNIQUE ( cpf );


CREATE TABLE T_VETERINARIAN (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ) NOT NULL,
    account_id  NUMBER NOT NULL,
    fullName    VARCHAR2(255) NOT NULL,
    cpf         VARCHAR2(14) NOT NULL,
    crmv        VARCHAR2(20) NOT NULL,
    speciality  VARCHAR2(100)
) LOGGING;

ALTER TABLE T_VETERINARIAN ADD CONSTRAINT T_Veterinarian_PK PRIMARY KEY ( id );
ALTER TABLE T_VETERINARIAN ADD CONSTRAINT uk_t_vet_account UNIQUE ( account_id );
ALTER TABLE T_VETERINARIAN ADD CONSTRAINT uk_t_vet_cpf UNIQUE ( cpf );
ALTER TABLE T_VETERINARIAN ADD CONSTRAINT uk_t_vet_crmv UNIQUE ( crmv );


CREATE TABLE T_PET (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ) NOT NULL,
    responsible_id NUMBER NOT NULL,
    name           VARCHAR2(100) NOT NULL,
    species        VARCHAR2(50) NOT NULL,
    breed          VARCHAR2(50),
    gender         VARCHAR2(10),
    birthDate      DATE,
    weight         NUMBER(5,2),
    currentStatus  VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
    createdAt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) LOGGING;

ALTER TABLE T_PET ADD CONSTRAINT chk_t_pet_status CHECK (currentStatus IN ('ATTENTION', 'NORMAL', 'RISK'));
ALTER TABLE T_PET ADD CONSTRAINT T_Pet_PK PRIMARY KEY ( id );


CREATE TABLE T_PET_VETERINARIAN (
    pet_id          NUMBER NOT NULL,
    veterinarian_id NUMBER NOT NULL,
    linkedAt        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) LOGGING;

ALTER TABLE T_PET_VETERINARIAN ADD CONSTRAINT T_Pet_Veterinarian_PK PRIMARY KEY ( pet_id, veterinarian_id );


CREATE TABLE T_CLINICALHISTORY (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ) NOT NULL,
    pet_id        NUMBER NOT NULL,
    temperature   NUMBER(4,1),
    heartRate     NUMBER(3),
    activityLevel VARCHAR2(50),
    healthScore   NUMBER(3),
    description   VARCHAR2(1000),
    observations  VARCHAR2(1000),
    recordedAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) LOGGING;

ALTER TABLE T_CLINICALHISTORY ADD CONSTRAINT T_ClinicalHistory_PK PRIMARY KEY ( id );


CREATE TABLE T_ALERT (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ) NOT NULL,
    pet_id     NUMBER NOT NULL,
    type       VARCHAR2(20) NOT NULL,
    message    VARCHAR2(500) NOT NULL,
    riskLevel  VARCHAR2(10) NOT NULL,
    status     VARCHAR2(15) DEFAULT 'OPEN' NOT NULL,
    createdAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolvedAt TIMESTAMP
) LOGGING;

ALTER TABLE T_ALERT ADD CONSTRAINT chk_t_alert_type CHECK (type IN ('BEHAVIOR_CHANGE', 'GENERAL', 'HEART_RATE', 'LOW_ACTIVITY', 'TEMPERATURE'));
ALTER TABLE T_ALERT ADD CONSTRAINT chk_t_alert_risk CHECK (riskLevel IN ('HIGH', 'LOW', 'MEDIUM'));
ALTER TABLE T_ALERT ADD CONSTRAINT chk_t_alert_status CHECK (status IN ('OPEN', 'RESOLVED', 'VIEWED'));
ALTER TABLE T_ALERT ADD CONSTRAINT T_Alert_PK PRIMARY KEY ( id );


CREATE TABLE T_APPOINTMENT (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ) NOT NULL,
    pet_id          NUMBER NOT NULL,
    veterinarian_id NUMBER NOT NULL,
    appointmentDate TIMESTAMP NOT NULL,
    reason          VARCHAR2(500),
    diagnosis       VARCHAR2(1000),
    recommendation  VARCHAR2(1000),
    status          VARCHAR2(15) DEFAULT 'SCHEDULED' NOT NULL,
    createdAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) LOGGING;

ALTER TABLE T_APPOINTMENT ADD CONSTRAINT chk_t_appointment_status CHECK (status IN ('CANCELED', 'COMPLETED', 'SCHEDULED'));
ALTER TABLE T_APPOINTMENT ADD CONSTRAINT T_Appointment_PK PRIMARY KEY ( id );


CREATE TABLE T_LOG_ERROS_PG (
    id_log        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_proc     VARCHAR2(100),
    usuario_bd    VARCHAR2(100),
    data_erro     DATE DEFAULT SYSDATE,
    codigo_erro   NUMBER,
    mensagem_erro VARCHAR2(4000)
);


--- =====================================================================
--- 3. CRIAÇÃO DAS CHAVES ESTRANGEIRAS (RELACIONAMENTOS)
--- =====================================================================
ALTER TABLE T_ALERT ADD CONSTRAINT fk_t_alert_pet_pg FOREIGN KEY ( pet_id ) REFERENCES T_PET ( id ) ON DELETE CASCADE;
ALTER TABLE T_APPOINTMENT ADD CONSTRAINT fk_t_appointment_pet_pg FOREIGN KEY ( pet_id ) REFERENCES T_PET ( id );
ALTER TABLE T_APPOINTMENT ADD CONSTRAINT fk_t_appointment_vet_pg FOREIGN KEY ( veterinarian_id ) REFERENCES T_VETERINARIAN ( id );
ALTER TABLE T_CLINICALHISTORY ADD CONSTRAINT fk_t_history_pet_pg FOREIGN KEY ( pet_id ) REFERENCES T_PET ( id ) ON DELETE CASCADE;
ALTER TABLE T_PET_VETERINARIAN ADD CONSTRAINT fk_t_link_pet_pg FOREIGN KEY ( pet_id ) REFERENCES T_PET ( id ) ON DELETE CASCADE;
ALTER TABLE T_PET_VETERINARIAN ADD CONSTRAINT fk_t_link_vet_pg FOREIGN KEY ( veterinarian_id ) REFERENCES T_VETERINARIAN ( id ) ON DELETE CASCADE;
ALTER TABLE T_PET ADD CONSTRAINT fk_t_pet_responsible_pg FOREIGN KEY ( responsible_id ) REFERENCES T_RESPONSIBLE ( id );
ALTER TABLE T_RESPONSIBLE ADD CONSTRAINT fk_t_responsible_account_pg FOREIGN KEY ( account_id ) REFERENCES T_ACCOUNT ( id ) ON DELETE CASCADE;
ALTER TABLE T_VETERINARIAN ADD CONSTRAINT fk_t_veterinarian_account_pg FOREIGN KEY ( account_id ) REFERENCES T_ACCOUNT ( id ) ON DELETE CASCADE;

COMMIT;


--- =====================================================================
--- 4. PROCEDURES DE CARGA DE DADOS COM TRATAMENTO EMBUTIDO
--- =====================================================================

CREATE OR REPLACE PROCEDURE pr_insert_account (
    p_email     IN VARCHAR2,
    p_password  IN VARCHAR2,
    p_role      IN VARCHAR2,
    p_active    IN NUMBER DEFAULT 1
) AS
    ex_invalid_role EXCEPTION;
    PRAGMA EXCEPTION_INIT(ex_invalid_role, -2290);
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    IF p_role NOT IN ('ADMIN', 'RESPONSIBLE', 'VETERINARIAN') THEN
        RAISE ex_invalid_role;
    END IF;

    INSERT INTO T_ACCOUNT (email, password, role, active)
    VALUES (p_email, p_password, p_role, p_active);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM || ' [Email: '|| p_email ||']', 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_ACCOUNT', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_account;
/

CREATE OR REPLACE PROCEDURE pr_insert_responsible (
    p_account_id  IN NUMBER,
    p_fullName    IN VARCHAR2,
    p_cpf         IN VARCHAR2,
    p_dateOfBirth IN DATE,
    p_phoneNumber IN VARCHAR2,
    p_address     IN VARCHAR2
) AS
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    INSERT INTO T_RESPONSIBLE (account_id, fullName, cpf, dateOfBirth, phoneNumber, address)
    VALUES (p_account_id, p_fullName, p_cpf, p_dateOfBirth, p_phoneNumber, p_address);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM || ' [CPF: '|| p_cpf ||']', 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_RESPONSIBLE', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_responsible;
/

CREATE OR REPLACE PROCEDURE pr_insert_veterinarian (
    p_account_id IN NUMBER,
    p_fullName   IN VARCHAR2,
    p_cpf        IN VARCHAR2,
    p_crmv       IN VARCHAR2,
    p_speciality IN VARCHAR2
) AS
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    INSERT INTO T_VETERINARIAN (account_id, fullName, cpf, crmv, speciality)
    VALUES (p_account_id, p_fullName, p_cpf, p_crmv, p_speciality);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM || ' [CRMV: '|| p_crmv ||']', 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_VETERINARIAN', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_veterinarian;
/

CREATE OR REPLACE PROCEDURE pr_insert_pet (
    p_responsible_id IN NUMBER,
    p_name           IN VARCHAR2,
    p_species        IN VARCHAR2,
    p_breed          IN VARCHAR2,
    p_gender         IN VARCHAR2,
    p_birthDate      IN DATE,
    p_weight         IN NUMBER,
    p_currentStatus  IN VARCHAR2 DEFAULT 'NORMAL'
) AS
    ex_invalid_status EXCEPTION;
    PRAGMA EXCEPTION_INIT(ex_invalid_status, -2290);
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    IF p_currentStatus NOT IN ('ATTENTION', 'NORMAL', 'RISK') THEN
        RAISE ex_invalid_status;
    END IF;

    INSERT INTO T_PET (responsible_id, name, species, breed, gender, birthDate, weight, currentStatus)
    VALUES (p_responsible_id, p_name, p_species, p_breed, p_gender, p_birthDate, p_weight, p_currentStatus);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM || ' [Nome Pet: '|| p_name ||']', 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_PET', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_pet;
/

CREATE OR REPLACE PROCEDURE pr_insert_pet_vet (
    p_pet_id          IN NUMBER,
    p_veterinarian_id IN NUMBER
) AS
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    INSERT INTO T_PET_VETERINARIAN (pet_id, veterinarian_id)
    VALUES (p_pet_id, p_veterinarian_id);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM || ' [Pet ID: '|| p_pet_id ||']', 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_PET_VET', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_pet_vet;
/

CREATE OR REPLACE PROCEDURE pr_insert_clinical_history (
    p_pet_id        IN NUMBER,
    p_temperature   IN NUMBER,
    p_heartRate     IN NUMBER,
    p_activityLevel IN VARCHAR2,
    p_healthScore   IN NUMBER,
    p_description   IN VARCHAR2,
    p_observations  IN VARCHAR2,
    p_retroativo_min IN NUMBER DEFAULT 0
) AS
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    INSERT INTO T_CLINICALHISTORY (pet_id, temperature, heartRate, activityLevel, healthScore, description, observations, recordedAt)
    VALUES (p_pet_id, p_temperature, p_heartRate, p_activityLevel, p_healthScore, p_description, p_observations, SYSTIMESTAMP - NUMTODSINTERVAL(p_retroativo_min, 'MINUTE'));
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM, 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_CLINICAL_HISTORY', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_clinical_history;
/

CREATE OR REPLACE PROCEDURE pr_insert_alert (
    p_pet_id    IN NUMBER,
    p_type      IN VARCHAR2,
    p_message   IN VARCHAR2,
    p_riskLevel IN VARCHAR2,
    p_status    IN VARCHAR2 DEFAULT 'OPEN'
) AS
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    INSERT INTO T_ALERT (pet_id, type, message, riskLevel, status)
    VALUES (p_pet_id, p_type, p_message, p_riskLevel, p_status);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM, 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_ALERT', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_alert;
/

CREATE OR REPLACE PROCEDURE pr_insert_appointment (
    p_pet_id          IN NUMBER,
    p_veterinarian_id IN NUMBER,
    p_appointmentDate IN TIMESTAMP,
    p_reason          IN VARCHAR2,
    p_diagnosis       IN VARCHAR2,
    p_recommendation  IN VARCHAR2,
    p_status          IN VARCHAR2 DEFAULT 'SCHEDULED'
) AS
    v_msg VARCHAR2(4000);
    v_code NUMBER;
BEGIN
    INSERT INTO T_APPOINTMENT (pet_id, veterinarian_id, appointmentDate, reason, diagnosis, recommendation, status)
    VALUES (p_pet_id, p_veterinarian_id, p_appointmentDate, p_reason, p_diagnosis, p_recommendation, p_status);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM, 1, 3900);
        INSERT INTO T_LOG_ERROS_PG (nome_proc, usuario_bd, codigo_erro, mensagem_erro)
        VALUES ('PR_INSERT_APPOINTMENT', sys_context('USERENV', 'CURRENT_USER'), v_code, v_msg);
        COMMIT;
END pr_insert_appointment;
/


--- =====================================================================
--- 5. PROCESSAMENTO DE DADOS (ORDEM OPERACIONAL CORRIGIDA)
--- =====================================================================
BEGIN
    -- 5.1 CADASTRO DAS ACCOUNTS BASE (IDs Gerados automaticamente: 1, 2, 3, 4, 5, 6)
    pr_insert_account('manuela.soares@fiap.com', 'SenhaSegura123', 'RESPONSIBLE', 1);
    pr_insert_account('moises.oliveira@fiap.com', 'Moi12345!', 'RESPONSIBLE', 1);
    pr_insert_account('sofia.fontes@fiap.com', 'Sofi@2026', 'RESPONSIBLE', 1);
    pr_insert_account('carlos.mendes@vet.com', 'VetCardio99', 'VETERINARIAN', 1);
    pr_insert_account('amanda.silva@vet.com', 'VetGeral88', 'VETERINARIAN', 1);
    pr_insert_account('admin.clyvo@petguardian.com', 'RootPG2026', 'ADMIN', 1);
    COMMIT;
END;
/

BEGIN
    -- 5.2 PERFIS VINCULADOS (Mapeados cirurgicamente nos IDs correspondentes)
    pr_insert_responsible(1, 'Manuela de Lacerda Soares', '12345678901', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '11988887777', 'Avenida Paulista, 1000');
    pr_insert_responsible(2, 'Moisés Barsoti Andrade de Oliveira', '23456789012', TO_DATE('1998-05-15', 'YYYY-MM-DD'), '11977776666', 'Rua Augusta, 450');
    pr_insert_responsible(3, 'Sofia Siqueira Fontes', '34567890123', TO_DATE('2001-09-20', 'YYYY-MM-DD'), '11966665555', 'Alameda Lorena, 820');

    pr_insert_veterinarian(4, 'Dr. Carlos Mendes', '98765432100', 'CRMV-SP-9999', 'Cardiologia Veterinária');
    pr_insert_veterinarian(5, 'Dra. Amanda Silva', '87654321011', 'CRMV-SP-8888', 'Clínica Geral');
    COMMIT;
END;
/

BEGIN
    -- 5.3 CADASTRO DOS PETS (Vinculados aos donos corretos criados acima - IDs: 1, 2, 3)
    pr_insert_pet(1, 'Thor', 'Cachorro', 'Golden Retriever', 'Macho', TO_DATE('2021-05-10', 'YYYY-MM-DD'), 32.5, 'NORMAL');
    pr_insert_pet(1, 'Luna', 'Gato', 'Siamês', 'Fêmea', TO_DATE('2022-03-18', 'YYYY-MM-DD'), 4.2, 'ATTENTION');
    pr_insert_pet(2, 'Zeus', 'Cachorro', 'Pastor Alemão', 'Macho', TO_DATE('2020-11-02', 'YYYY-MM-DD'), 38.0, 'RISK');
    pr_insert_pet(2, 'Mia', 'Gato', 'Persa', 'Fêmea', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 3.8, 'NORMAL');
    pr_insert_pet(3, 'Mel', 'Cachorro', 'Poodle', 'Fêmea', TO_DATE('2019-07-22', 'YYYY-MM-DD'), 6.5, 'NORMAL');
    COMMIT;
END;
/

BEGIN
    -- 5.4 CRIAÇÃO DAS ASSOCIAÇÕES E ROTINAS CLÍNICAS (Mapeado nos IDs reais do banco: Pets 1 a 5, Vets 1 e 2)
    pr_insert_pet_vet(1, 1);
    pr_insert_pet_vet(2, 1);
    pr_insert_pet_vet(3, 2);
    pr_insert_pet_vet(4, 2);
    pr_insert_pet_vet(5, 1);

    -- 5.5 HISTÓRICOS CLÍNICOS MULTILINHAS (Garante o funcionamento perfeito do LAG/LEAD)
    pr_insert_clinical_history(1, 38.2, 90, 'NORMAL', 98, 'Dados estáveis via ESP32', 'Rotina matinal', 40);
    pr_insert_clinical_history(1, 38.9, 115, 'HIGH', 80, 'Pico detectado pós corrida', 'Atividade alta', 20);
    pr_insert_clinical_history(1, 39.5, 130, 'HIGH', 65, 'Febre e batimento elevado', 'Anomalia detectada', 0);
    pr_insert_clinical_history(2, 38.5, 110, 'NORMAL', 90, 'Coleta padrão diária', 'Estável', 0);
    pr_insert_clinical_history(3, 40.2, 145, 'LOW', 40, 'Animal letárgico com hipertermia', 'Alerta crítico emitido', 0);
    pr_insert_clinical_history(4, 37.8, 85, 'NORMAL', 95, 'Métricas excelentes', 'Padrão', 0);
    pr_insert_clinical_history(5, 38.4, 95, 'NORMAL', 97, 'Monitoramento OK', 'Sem alterações', 0);

    -- 5.6 ALERTAS PREVENTIVOS
    pr_insert_alert(1, 'TEMPERATURE', 'Temperatura atingiu 39.5C', 'MEDIUM', 'OPEN');
    pr_insert_alert(1, 'HEART_RATE', 'Frequência cardíaca em 130 bpm', 'HIGH', 'OPEN');
    pr_insert_alert(3, 'TEMPERATURE', 'Hipertermia severa detectada: 40.2C', 'HIGH', 'OPEN');
    pr_insert_alert(3, 'LOW_ACTIVITY', 'Nível de atividade extremamente baixo', 'MEDIUM', 'VIEWED');
    pr_insert_alert(2, 'BEHAVIOR_CHANGE', 'Mudança comportamental relatada pelo tutor', 'LOW', 'RESOLVED');

    -- 5.7 CONSULTAS E AGENDAMENTOS CLÍNICOS
    pr_insert_appointment(3, 1, SYSTIMESTAMP, 'Atendimento emergencial por febre', 'Gastroenterite ajuda', 'Medicação injetável e repouso', 'COMPLETED');
    pr_insert_appointment(1, 1, SYSTIMESTAMP + 2, 'Check-up cardiológico preventivo', NULL, NULL, 'SCHEDULED');
    pr_insert_appointment(2, 2, SYSTIMESTAMP + 3, 'Consulta de rotina felina', NULL, NULL, 'SCHEDULED');
    pr_insert_appointment(4, 2, SYSTIMESTAMP - 5, 'Vacinação Anual V10', 'Saudável', 'Reforço em 1 ano', 'COMPLETED');
    pr_insert_appointment(5, 1, SYSTIMESTAMP + 1, 'Avaliação de dor articular', NULL, NULL, 'SCHEDULED');
    pr_insert_appointment(1, 2, SYSTIMESTAMP + 4, 'Consulta cancelada pelo tutor', NULL, NULL, 'CANCELED');
    COMMIT;
END;
/

BEGIN
    -- 5.8 DISPAROS DE ERRO VOLUNTÁRIOS ISOLADOS (Auditoria obrigatória rica com mais de 5 logs de falha)
    pr_insert_account('manuela.soares@fiap.com', 'SenhaDuplicada', 'RESPONSIBLE'); 
    pr_insert_account('erro.role@fiap.com', 'Senha123', 'ROLE_ERRADA');           
    pr_insert_pet(999, 'PetOrfao', 'Cão', 'Srd', 'Macho', SYSDATE, 10);            
    pr_insert_pet_vet(999, 1);                                                     
    pr_insert_veterinarian(1, 'Duplicado', '12345678901', 'CRMV-1', 'Geral');     
    COMMIT;
END;
/


--- =====================================================================
--- 6. CURSORES EXPLICITOS COM AGREGADOS E TOMADA DE DECISÃO
--- =====================================================================

-- CURSOR EXPLICITO 1: Subtotais de Consultas por Status
DECLARE
    CURSOR c_consultas IS
        SELECT id, status, reason
        FROM T_APPOINTMENT
        ORDER BY status, id;

    v_status_anterior T_APPOINTMENT.status%TYPE := NULL;
    v_qtd_status      NUMBER := 0;
    v_total           NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== CURSOR 1: RELATÓRIO SUBSTOTALIZADO DE CONSULTAS =====');

    FOR consulta IN c_consultas LOOP
        IF v_status_anterior IS NOT NULL AND v_status_anterior <> consulta.status THEN
            DBMS_OUTPUT.PUT_LINE('>> Subtotal do status [' || v_status_anterior || ']: ' || v_qtd_status);
            DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------');
            v_qtd_status := 0;
        END IF;

        v_status_anterior := consulta.status;
        DBMS_OUTPUT.PUT_LINE('Consulta ID: ' || consulta.id || ' | Status: ' || consulta.status || ' | Motivo: ' || consulta.reason);
        
        v_qtd_status := v_qtd_status + 1;
        v_total      := v_total + 1;
    END LOOP;

    IF v_qtd_status > 0 THEN
        DBMS_OUTPUT.PUT_LINE('>> Subtotal do status [' || v_status_anterior || ']: ' || v_qtd_status);
    END IF;

    DBMS_OUTPUT.PUT_LINE('=========================================================');
    DBMS_OUTPUT.PUT_LINE('TOTAL GERAL DE CONSULTAS PROCESSADAS: ' || v_total);
END;
/

-- CURSOR EXPLICITO 2: Agregados Aritméticos de Histórico Clínico (AVG, COUNT) por Pet
DECLARE
    CURSOR c_historico IS
        SELECT p.name AS pet_name,
               ROUND(AVG(ch.temperature), 2) AS media_temperatura,
               ROUND(AVG(ch.heartRate), 2) AS media_batimentos,
               COUNT(ch.id) AS total_medicoes
        FROM T_PET p
        INNER JOIN T_CLINICALHISTORY ch ON ch.pet_id = p.id
        GROUP BY p.name
        ORDER BY p.name;
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== CURSOR 2: AGREGADOS DE SAÚDE MÉDIA POR PACIENTE =====');
    FOR reg IN c_historico LOOP
        DBMS_OUTPUT.PUT_LINE('Pet: ' || RPAD(reg.pet_name, 12) || 
                             ' | Média Temp: ' || reg.media_temperatura || '°C' ||
                             ' | Média Batimentos: ' || LPAD(reg.media_batimentos, 6) || ' bpm' ||
                             ' | Total Medições: ' || reg.total_medicoes);
    END LOOP;
END;
/

-- CURSOR EXPLICITO 3: Triagem Operacional de Pets com Tomada de Decisão
DECLARE
    CURSOR c_triagem IS
        SELECT name, currentStatus
        FROM T_PET
        ORDER BY currentStatus DESC;
    v_criticos NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== CURSOR 3: TRIAGEM OPERACIONAL DE PACIENTES =====');
    FOR pet IN c_triagem LOOP
        IF pet.currentStatus = 'RISK' THEN
            DBMS_OUTPUT.PUT_LINE('[ALERTA CRÍTICO] O paciente ' || pet.name || ' encontra-se em estado de RISCO!');
            v_criticos := v_criticos + 1;
        ELSIF pet.currentStatus = 'ATTENTION' THEN
            DBMS_OUTPUT.PUT_LINE('[ATENÇÃO] O paciente ' || pet.name || ' necessita de acompanhamento contínuo.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('[ESTÁVEL] O paciente ' || pet.name || ' apresenta parâmetros estáveis.');
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Total de pacientes críticos em atenção imediata: ' || v_criticos);
END;
/

-- CURSOR EXPLICITO 4: Varredura de Auditoria de Logs de Erro Gerados
DECLARE
    CURSOR c_logs IS
        SELECT nome_proc, codigo_erro, mensagem_erro
        FROM T_LOG_ERROS_PG
        ORDER BY id_log;
    v_qtd NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== CURSOR 4: AUDITORIA INTERNA DO SISTEMA (LOGS) =====');
    FOR erro IN c_logs LOOP
        v_qtd := v_qtd + 1;
        DBMS_OUTPUT.PUT_LINE('Falha #' || v_qtd || ' | Routine: ' || erro.nome_proc || 
                             ' | Oracle Error: ORA-' || LPAD(ABS(erro.codigo_erro), 5, '0') || 
                             ' | Detalhe: ' || SUBSTR(erro.mensagem_erro, 1, 65));
    END LOOP;
END;
/


--- =====================================================================
--- 7. SEÇÃO DE BLOCOS DE ANÁLISE TEMPORAL (FUNÇÃO ANALÍTICA - LAG/LEAD)
--- =====================================================================
DECLARE
    CURSOR c_analitico IS
        SELECT pet_id AS id,
               TO_CHAR(recordedAt, 'DD/MM/YYYY HH24:MI') AS dt,
               NVL(TO_CHAR(LAG(temperature, 1) OVER (PARTITION BY pet_id ORDER BY recordedAt)), 'Início') AS ant,
               TO_CHAR(temperature) AS atual,
               NVL(TO_CHAR(LEAD(temperature, 1) OVER (PARTITION BY pet_id ORDER BY recordedAt)), 'Final') AS prox
        FROM T_CLINICALHISTORY;
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== SEÇÃO 7: MONITORAMENTO ANALÍTICO DE SENSOR (LAG/LEAD) =====');
    FOR r IN c_analitico LOOP
        DBMS_OUTPUT.PUT_LINE('ID Pet: ' || r.id || ' | Data/Hora: ' || r.dt || 
                             ' | Métrica Anterior: ' || RPAD(r.ant, 6) || 
                             ' | Leitura Atual: ' || RPAD(r.atual, 5) || 
                             ' | Próxima Leitura: ' || r.prox);
    END LOOP;
END;
/

